#!/bin/bash
# 为WordPress站点生成应用程序密码的说明

echo "=========================================="
echo "WordPress应用程序密码配置指南"
echo "=========================================="
echo ""
echo "由于WordPress REST API需要应用程序密码，请按以下步骤操作："
echo ""
echo "方案1：手动在WordPress后台生成（推荐）"
echo "----------------------------------------"
echo "1. 访问 http://a.com/wp-admin/"
echo "2. 使用 admin/admin 登录"
echo "3. 进入 用户 -> 个人资料"
echo "4. 滚动到底部找到 '应用程序密码' 部分"
echo "5. 输入名称（如：荣耀AI系统）"
echo "6. 点击 '添加新应用程序密码'"
echo "7. 复制生成的密码（格式：xxxx xxxx xxxx xxxx xxxx xxxx）"
echo ""
echo "然后运行以下命令更新数据库："
echo "sudo docker-compose exec backend python -c \""
echo "import asyncio"
echo "from app.database import get_db"
echo "from app.services.wordpress_site_service import WordPressSiteService"
echo ""
echo "async def update():"
echo "    async for db in get_db():"
echo "        service = WordPressSiteService(db)"
echo "        await service.update_site(8, api_password='你的应用程序密码')"
echo "        print('✅ 密码已更新')"
echo "        break"
echo "asyncio.run(update())"
echo "\""
echo ""
echo "方案2：使用测试密码（仅用于开发）"
echo "----------------------------------------"
echo "运行以下命令设置测试密码："
echo ""
echo "sudo docker-compose exec backend python setup_wp_test_password.py"
echo ""
echo "=========================================="
